### ISSUE TITLE
Setup django celery beat

### ISSUE THREAD

**Issue by Bryce-VE** [mrcrowley42/Project5#11]
Setting up django-celery-beat with automatic periodic tasks

**Comment by Bryce-VE** [comment]
Instructions to use celery are in the README and SETUP files

**Comment by mnewbery** [comment]
Rejected - definition of done = "We aren't changing the code any more"

In order for this code to be accepted please

Remove the debug task on celery.py lines 16-20.
Remove the debug task on tasks.py lines 5-8.

A separate issue to "Build out the update data task to ensure the call to BOM results in new data being ingested" will be created

**Comment by mnewbery** [comment]
Reviewed sucessfully
