### ISSUE TITLE
Save observations for test data

### ISSUE THREAD

**Issue by mrcrowley42** [mrcrowley42/Project5#4]

**Comment by mnewbery** [comment]
In the data folder there is source JSON, a python file that converts multiple JSON files to a single CSV and removes duplicates while the CSV is output. In the same folder, test2.csv appears. This can be used to upload test and historical data for anyone who needs it. A few more days of historical data can be generated in this way after downloading a few more JSON files as seen in the URLs for the readme.md in the data folder

**Comment by mrcrowley42** [comment]
I've made the change to remove duplicates, in migration 2, line 21

**Comment by mnewbery** [comment]
Reviewed successfully. There should be unit tests for the changes but we will ignore the lack of coverage for now
